# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Codecov
      run: npm install -g codecov

    - name: Run CI for Anaconda
      working-directory: Anaconda
      run: |
           npm ci
           npm run build --if-present
           npm test -- --coverage

    - name: Run CI for Justificar
      working-directory: Justificar
      run: |
           npm ci
           npm run build --if-present
           npm test -- --coverage

    - name: Run CI for Palindromo
      working-directory: Palindromo
      run: |
           npm ci
           npm run build --if-present
           npm test -- --coverage

    - name: Run CI for SortingUniqueAnagrams
      working-directory: SortingUniqueAnagrams
      run: |
           npm ci
           npm run build --if-present
           npm test -- --coverage

    - name: Run CI for AparearValores
      working-directory: AparearValores
      run: |
           npm ci
           npm run build --if-present
           npm test -- --coverage

    - name: Run CI for MalwareAnalysis
      working-directory: MalwareAnalysis
      run: |
           npm ci
           npm run build --if-present
           npm test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5

